import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { GlobalStyle } from '@/styles/global'
import Providers from '@/lib/providers'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Github Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <Providers>
          <GlobalStyle />
          { children }
        </Providers>
      </body>
    </html>
  )
}
